### ISSUE TITLE
Error of Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by Rozaki0318** [Shahrayar123/Python-Projects#149]
I have played Tic-Tac-Toe Game and found a following error. 
Could you assign this to me ?

```
$ python3 TicTacToe.py 
Do you want to play a game (Y/N): Y
-----------------------------------------
Welcome to the tic tac toe game

   |   |   
   |   |  
   |   |   
-----------
   |   |   
   |   |  
   |   |   
-----------
   |   |   
   |   |  
   |   |   

...

Enter a position between 1 to 9: 4
   |   |   
 X | O | X
   |   |   
-----------
   |   |   
 X | X | O
   |   |   
-----------
   |   |   
 O | X | O
   |   |   
Traceback (most recent call last):
  File "TicTacToe.py", line 136, in <module>
    main()
  File "TicTacToe.py", line 119, in main
    insertLetter("O", move)
  File "TicTacToe.py", line 4, in insertLetter
    board[pos] = letter
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by Rozaki0318** [comment]
I have already submit [pull request](https://github.com/Shahrayar123/Python-Projects/pull/150) for this issue, so this issue is not needed any more.
